---
title: "Analysis - Team Safe Istanbul"

format:
  html:
    code-fold: true
    code-summary: "Show the code"
---

## Analysis of "Eartquake Analysis and Results Data"

```{r, message=FALSE}
    library(dplyr)
    library(readr)
    library(knitr)
    library(ggplot2)
    library(leaflet)
    library(readxl)
    library(gridExtra)
    
    deprem_analiz <- read.csv("Deprem_senaryosu_analiz_sonuçlar.csv")
    deprem_analiz$ilce_adi <- gsub("Ý", "İ", deprem_analiz$ilce_adi, fixed = TRUE)
    deprem_analiz$ilce_adi <- gsub("Ð", "Ğ", deprem_analiz$ilce_adi, fixed = TRUE)
    deprem_analiz$ilce_adi <- gsub("Þ", "Ş", deprem_analiz$ilce_adi, fixed = TRUE)
    deprem_analiz$ilce_adi <- gsub("Þ", "Ş", deprem_analiz$ilce_adi, fixed = TRUE)
    
    deprem_analiz <- data.frame(lapply(deprem_analiz, function(v) {
      if (is.character(v)) return(tolower(v))
      else return(v)
    }))
    
    nufus <- read_excel("belediye_nufuslar_2019.xlsx")
    nufus <- data.frame(lapply(nufus, function(v) {
      if (is.character(v)) return(tolower(v))
      else return(v)
    }))
    nufus$Belediyeler <- gsub("belediyesi", "", nufus$Belediyeler)
   

    istanbul_coordinates <- read.csv("istanbul_koordinatlar.csv")
    istanbul_coordinates <- data.frame(lapply(istanbul_coordinates, function(v) {
      if (is.character(v)) return(tolower(v))
      else return(v)
    }))    
    

istanbul_df <- data.frame(read_excel("istanbul_df.xlsx"))
istanbul_df <- cbind(istanbul_df, nufus)
istanbul_df <- istanbul_df %>% 
  select(-Belediyeler) %>% 
  select(ilce_adi, X2019.yılı.nüfusları, cok_agir_hasarli_bina_sayisi:last_col())

    
    colnames(deprem_analiz)[1:4] <- c("id", "ilce_adi", "mahalle_adi", "mahalle_kodu")
    district_sum <- deprem_analiz %>% group_by(ilce_adi) %>% summarise(
                                                                  total_cok_agir_hasarli = sum(cok_agir_hasarli_bina_sayisi),
                                                                  total_agir_hasarli = sum(agir_hasarli_bina_sayisi),
                                                                  total_orta_hasarli = sum(orta_hasarli_bina_sayisi),
                                                                  total_hafif_hasarli = sum(hafif_hasarli_bina_sayisi),
                                                                  total_can_kaybi = sum(can_kaybi_sayisi),
                                                                  total_agir_yarali = sum(agir_yarali_sayisi),
                                                                  total_hafif_yarali = sum(hafif_yarali_sayisi),
                                                                  .groups = 'drop')
    
district_sum <- data.frame(district_sum)


    district_avg <- deprem_analiz %>% group_by(ilce_adi) %>% summarise(
                                                                  avg_cok_agir_hasarli = mean(cok_agir_hasarli_bina_sayisi),
                                                                  avg_agir_hasarli = mean(agir_hasarli_bina_sayisi),
                                                                  avg_orta_hasarli = mean(orta_hasarli_bina_sayisi),
                                                                  avg_hafif_hasarli = mean(hafif_hasarli_bina_sayisi),
                                                                  avg_can_kaybi = mean(can_kaybi_sayisi),
                                                                  avg_agir_yarali = mean(agir_yarali_sayisi),
                                                                  avg_hafif_yarali = mean(hafif_yarali_sayisi),
                                                                 .groups = 'drop')
    district_avg$ilce_adi <- factor(district_avg$ilce_adi, levels = unique(district_avg$ilce_adi))
    
    kable(head(district_avg, 10), caption="Data")
```

```{r, message=FALSE}
    building_avg_line <- ggplot(district_avg, aes(x = ilce_adi)) +
                geom_line(aes(y = avg_cok_agir_hasarli, group = 1, color = "Çok Ağır Hasarlı")) +
                geom_line(aes(y = avg_agir_hasarli, group = 1, color = "Ağır Hasarlı")) +
                geom_line(aes(y = avg_orta_hasarli, group = 1, color = "Orta Hasarlı")) +
                geom_line(aes(y = avg_hafif_hasarli, group = 1, color = "Hafif Hasarlı")) +
                ylab("Ortalama Bina Sayısı") +
                xlab("İlçe Adı") +
                ggtitle("Deprem Hasar Analizi İlçe Bazında Ortalamalar (Line Chart)") +
                theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
                scale_color_manual(values = c("Çok Ağır Hasarlı" = "red", "Ağır Hasarlı" = "orange", 
                                              "Orta Hasarlı" = "blue", "Hafif Hasarlı" = "black"))
  
    building_avg_bar <- ggplot(district_avg, aes(x = ilce_adi)) +
                geom_bar(aes(y = avg_hafif_hasarli), fill = "black", position = "dodge", stat = "identity") +
                geom_bar(aes(y = avg_orta_hasarli), fill = "blue", position = "dodge", stat = "identity") +
                geom_bar(aes(y = avg_agir_hasarli), fill = "orange", position = "dodge", stat = "identity") +
                geom_bar(aes(y = avg_cok_agir_hasarli), fill = "red", position = "dodge", stat = "identity") +
                ylab("Ortalama Bina Sayısı") +
                xlab("İlçe Adı") +
                ggtitle("Deprem Hasar Analizi İlçe Bazında Ortalamalar")+
                theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

    avg_health <- ggplot(district_avg, aes(x = ilce_adi)) +
                geom_line(aes(y = avg_can_kaybi, group = 1, color = "Can Kaybı")) +
                geom_line(aes(y = avg_agir_yarali, group = 1, color = "Ağır Yaralı")) +
                geom_line(aes(y = avg_hafif_yarali, group = 1, color = "Hafif Yaralı")) +
                ylab("Yaralanma ve Can Kaybi") +
                xlab("İlçe Adı") +
                ggtitle("Deprem Hasar Analizi İlçe Bazında Ortalamalar (Line Chart)") +
                theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) +
                scale_color_manual(values = c("Can Kaybı" = "black", "Ağır Yaralı" = "red", 
                                              "Hafif Yaralı" = "blue"))
    
    

```

### average health

```{r, message=FALSE}
avg_health
```

### average building

```{r, message=FALSE}
  building_avg_bar
```

### average building line

```{r, message=FALSE}
  building_avg_line
```

### danger zone calc

```{r, message=FALSE}
    danger_level <- as.numeric(district_sum$total_cok_agir_hasarli * district_avg$avg_can_kaybi)
    istanbul_coordinates$danger_level <- as.numeric(format(danger_level, scientific = FALSE))
    istanbul_coordinates <- istanbul_coordinates[order(istanbul_coordinates$danger_level, decreasing = TRUE),]
    
    istanbul_coordinates$color <- ifelse(istanbul_coordinates$danger_level > mean(istanbul_coordinates$danger_level), "red", "blue")
    istanbul_coordinates$danger_level <- format(istanbul_coordinates$danger_level, scientific = FALSE)
    
    kable(head(istanbul_coordinates, 10), caption = "istanbul something.")

```

### Death/Population
```{r, message=FALSE}
    istanbul_df %>%
  select(ilce_adi, X2019.yılı.nüfusları, can_kaybi_sayisi) %>%
  ggplot(aes(x = ilce_adi, y = can_kaybi_sayisi)) +
  geom_point(aes(size = X2019.yılı.nüfusları, color = cut(((can_kaybi_sayisi / X2019.yılı.nüfusları) * 1000), 
                                                          breaks = c(0, 0.7, 2, 5), 
                                                          labels = c("Least Dangerous", "Medium Dangerous", "High Dangerous")))) +
  scale_color_manual(values = c("High Dangerous" = "red", "Medium Dangerous" = "blue", "Least Dangerous" = "green"))+
  theme_bw()+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1), legend.position = "none") +
  xlab("District") +
  ylab("Death") +
  scale_y_continuous(limits = c(0, max(istanbul_df$can_kaybi_sayisi) * 1.1)) +
  scale_size_continuous(range=c(2,8))

```

### danger zone map

```{r, message=FALSE}

    harita <- leaflet(istanbul_coordinates) %>%
      addTiles() %>%
      addCircleMarkers(
        lng = ~longitude,
        lat = ~latitude,
        radius = 10,
        color = ~color,
        fillOpacity = 0.5,
        popup = ~paste(ilceler, ": ", danger_level)
      )

    harita
```

### Bina - Tesisat Hasar Türleri ve Can Kaybı Arasındaki İlişki
#### Bina Hasar vs Can Kaybı
```{r, message=FALSE}
    cor_func <- function(x, y) {
  cor_coef <- cor(x, y)
  cor_label <- paste("Correlation:", round(cor_coef, 3))
  return(cor_label)
}

plot1 <- ggplot(istanbul_df, aes(x = cok_agir_hasarli_bina_sayisi)) +
  geom_point(aes(y = can_kaybi_sayisi), color = "blue") +
  geom_smooth(aes(y = can_kaybi_sayisi), method = "lm", se = TRUE, color = "blue") +
  geom_text(aes(x = min(cok_agir_hasarli_bina_sayisi), y = max(can_kaybi_sayisi), label = cor_func(can_kaybi_sayisi, cok_agir_hasarli_bina_sayisi)), 
            hjust = 0, vjust = -2.5, color = "black") +
  theme_minimal() +
  facet_wrap(~"Çok Ağır Hasarlı Bina Sayısı", scales = "free") +
  ylab("") + xlab("")

plot2 <- ggplot(istanbul_df, aes(x = agir_hasarli_bina_sayisi)) +
  geom_point(aes(y = can_kaybi_sayisi), color = "red") +
  geom_smooth(aes(y = can_kaybi_sayisi), method = "lm", se = TRUE, color = "red") +
  geom_text(aes(x = min(agir_hasarli_bina_sayisi), y = max(can_kaybi_sayisi), label = cor_func(can_kaybi_sayisi, agir_hasarli_bina_sayisi)), 
            hjust = 0, vjust = -1, color = "black") +
  theme_minimal() +
  facet_wrap(~"Ağır Hasarlı Bina Sayısı", scales = "free") +
  ylab("") + xlab("")

plot3 <- ggplot(istanbul_df, aes(x = orta_hasarli_bina_sayisi)) +
  geom_point(aes(y = can_kaybi_sayisi), color = "green") +
  geom_smooth(aes(y = can_kaybi_sayisi), method = "lm", se = TRUE, color = "green") +
  geom_text(aes(x = min(orta_hasarli_bina_sayisi), y = max(can_kaybi_sayisi), label = cor_func(can_kaybi_sayisi, orta_hasarli_bina_sayisi)), 
            hjust = 0, vjust = 1, color = "black") +
  theme_minimal() +
  facet_wrap(~"Orta Hasarlı Bina Sayısı", scales = "free") +
  ylab("") + xlab("")

plot4 <- ggplot(istanbul_df, aes(x = hafif_hasarli_bina_sayisi)) +
  geom_point(aes(y = can_kaybi_sayisi), color = "purple") +
  geom_smooth(aes(y = can_kaybi_sayisi), method = "lm", se = TRUE, color = "purple") +
  geom_text(aes(x = min(hafif_hasarli_bina_sayisi), y = max(can_kaybi_sayisi), label = cor_func(can_kaybi_sayisi, hafif_hasarli_bina_sayisi)), 
            hjust = 0, vjust = 1, color = "black") +
  theme_minimal() +
  facet_wrap(~"Hafif Hasarlı Bina Sayısı", scales = "free") +
  ylab("") + xlab("")

grid.arrange(plot1, plot2, plot3, plot4, ncol = 2)
```


#### Tesisat Hasar vs Can Kaybı
```{r, message=FALSE}

```

