---
title: "Data"

format:
  html:
    code-fold: true
    code-summary: "Show the code"
---

Datasets shown below downloaded from [Istanbul Metropolitan Municipality](data.ibb.gov.tr) website as csv and xlsx files. Separate links are also provided.

# Data Sets

1.  [Earthquake Scenario Analysis Results](https://data.ibb.gov.tr/tr/dataset/deprem-senaryosu-analiz-sonuclari/resource/9c3ac492-de4b-4245-b418-7ad3df67a193)

    ```{r}

    library(readr)
    deprem_analiz <- read.csv("Deprem_senaryosu_analiz_sonuçlar.csv")
    colnames(deprem_analiz)[1:4] <- c("id", "ilce_adi", "mahalle_adi", "mahalle_kodu")
    str(deprem_analiz)
    head(deprem_analiz, n = 10L)

    ```

2.  [Neighborhood-Based Building Numbers in 2017](https://data.ibb.gov.tr/tr/dataset/mahalle-bazli-bina-analiz-verisi/resource/cef193d5-0bd2-4e8d-8a69-275c50288875)

    ```{r}
    library(dplyr)
    library(readr)
    mahalle_bazli_bina <- read.csv("mahalle_bazli_bina_2017.csv")
    colnames(mahalle_bazli_bina) <- c("id", "ilce_adi", "mahalle_adi", "mahalle_kodu", "once_1980", "ara_1980_2000", "sonra_2000", "ara_1_4_kat", "ara_5_9_kat", "ara_9_19_kat")
    toplam_bina <- mahalle_bazli_bina %>% 
      select(ara_1_4_kat,ara_5_9_kat,ara_9_19_kat) %>%
      rowwise() %>%
      do( (.) %>% as.data.frame() %>% mutate(toplam_bina = sum(.))) %>%
      ungroup %>%
      select(toplam_bina)
    mahalle_bazli_bina <- cbind(mahalle_bazli_bina, toplam_bina)
    str(mahalle_bazli_bina)
    head(mahalle_bazli_bina, n = 10L)
    ```

    ```{r}
    #mahalle_bazli_bina %>% 
      #group_by(ilce_adi) %>%
      #summarize(ilce_bazli_bina = sum(toplam_bina)) %>%
      #arrange(ilce_bazli_bina) %>% 
      #ggplot(aes(ilce_bazli_bina, fill = ilce_adi)) + geom_histogram(binwidth = 4000)





    ```

3.  [Municipality Population in 2019](https://data.ibb.gov.tr/tr/dataset/belediye-nufuslari-veri-seti/resource/c6c9b289-2824-41b3-ab3d-4fd655ed4e24)

    ```{r}

    library(readxl)
    nufus <- read_excel("belediye_nufuslar_2019.xlsx")
    str(nufus)
    head(nufus, n = 10L)

    ```
